name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверка кода
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Копирование файлов проекта на сервер
      - name: Upload project files to server
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/var/www/html/api.rechip-tuning.ru"
          rm: false  # Не удалять файлы на сервере
          excludes: |
            storage/app/public

      # Шаг 3: Выполнение команд на сервере
      - name: Run deployment commands on server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/api.rechip-tuning.ru

            # Установка зависимостей на сервере (устанавливает зависимости из composer.lock)
            composer install --no-dev --optimize-autoloader

            # Выполнение миграций (если необходимо)
            php artisan migrate --force

            # Очистка и обновление кэшей
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # Установка правильных прав для директорий
            chown -R www-data:www-data /var/www/html/api.rechip-tuning.ru
            chmod -R 755 /var/www/html/api.rechip-tuning.ru
            chmod -R 775 /var/www/html/api.rechip-tuning.ru/storage
            chmod -R 775 /var/www/html/api.rechip-tuning.ru/bootstrap/cache

            # Перезапуск PHP-FPM для версии 8.3
            sudo systemctl restart php8.3-fpm
